name: Build Test

on:
  pull_request:
    branchs:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
    matrix:
      python-version: "3.10"

    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest